// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJXmtMVVurlXiw56I0CuDwdEDYnb6Er6A',
    appId: '1:62074515787:web:94377cf866faf15097b8ce',
    messagingSenderId: '62074515787',
    projectId: 'ngogrid-c019b',
    authDomain: 'ngogrid-c019b.firebaseapp.com',
    storageBucket: 'ngogrid-c019b.firebasestorage.app',
    measurementId: 'G-0Y1PKBCQL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo_uufL8Apn6v6pN-cYl6SY1Me1Ebbleo',
    appId: '1:62074515787:android:23438b7699ba339197b8ce',
    messagingSenderId: '62074515787',
    projectId: 'ngogrid-c019b',
    storageBucket: 'ngogrid-c019b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHNu_HL2i2f9rJ9G8oZ-q5Ou__IlzhMJ4',
    appId: '1:62074515787:ios:0f5b7799e95461c097b8ce',
    messagingSenderId: '62074515787',
    projectId: 'ngogrid-c019b',
    storageBucket: 'ngogrid-c019b.firebasestorage.app',
    iosClientId: '62074515787-qnanr9fnh095pe1od65mv1lqhrddcvde.apps.googleusercontent.com',
    iosBundleId: 'com.example.ngoGridApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHNu_HL2i2f9rJ9G8oZ-q5Ou__IlzhMJ4',
    appId: '1:62074515787:ios:0f5b7799e95461c097b8ce',
    messagingSenderId: '62074515787',
    projectId: 'ngogrid-c019b',
    storageBucket: 'ngogrid-c019b.firebasestorage.app',
    iosClientId: '62074515787-qnanr9fnh095pe1od65mv1lqhrddcvde.apps.googleusercontent.com',
    iosBundleId: 'com.example.ngoGridApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJXmtMVVurlXiw56I0CuDwdEDYnb6Er6A',
    appId: '1:62074515787:web:771de69b717c43d697b8ce',
    messagingSenderId: '62074515787',
    projectId: 'ngogrid-c019b',
    authDomain: 'ngogrid-c019b.firebaseapp.com',
    storageBucket: 'ngogrid-c019b.firebasestorage.app',
    measurementId: 'G-T373VVVSWW',
  );

}